"""Scenario loading — YAML-based scenario configs that override generate_world output."""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml
from pydantic import BaseModel, Field

from chronicler.models import (
    ActiveCondition, Civilization, Disposition, Region, Relationship, TechEra, WorldState,
)
from chronicler.world_gen import DEFAULT_EVENT_PROBABILITIES, REGION_TEMPLATES


# Valid event types for probability overrides (M7 cascade types are NOT valid targets —
# tech_advancement, coup, legacy, rival_fall are generated by simulation mechanics, not rolled for)
VALID_EVENT_OVERRIDE_KEYS = set(DEFAULT_EVENT_PROBABILITIES.keys())


class EventFlavor(BaseModel):
    name: str
    description: str


class LeaderOverride(BaseModel):
    name: str | None = None
    trait: str | None = None


class RegionOverride(BaseModel):
    name: str
    terrain: str | None = None
    carrying_capacity: int | None = Field(default=None, ge=1, le=10)
    resources: str | None = None
    controller: str | None = None


class CivOverride(BaseModel):
    name: str
    population: int | None = Field(default=None, ge=1, le=10)
    military: int | None = Field(default=None, ge=1, le=10)
    economy: int | None = Field(default=None, ge=1, le=10)
    culture: int | None = Field(default=None, ge=1, le=10)
    stability: int | None = Field(default=None, ge=1, le=10)
    treasury: int | None = Field(default=None, ge=0)
    asabiya: float | None = Field(default=None, ge=0.0, le=1.0)
    tech_era: str | None = None
    domains: list[str] | None = None
    values: list[str] | None = None
    goal: str | None = None
    leader: LeaderOverride | None = None
    leader_name_pool: list[str] | None = None


class ConditionConfig(BaseModel):
    type: str
    affected: list[str]
    duration: int = Field(ge=1)
    severity: int = Field(ge=1, le=10)


class ScenarioConfig(BaseModel):
    name: str
    description: str = ""
    world_name: str | None = None
    seed: int | None = None
    num_civs: int | None = None
    num_regions: int | None = None
    num_turns: int | None = None
    reflection_interval: int | None = None
    regions: list[RegionOverride] = Field(default_factory=list)
    civilizations: list[CivOverride] = Field(default_factory=list)
    relationships: dict[str, dict[str, str]] = Field(default_factory=dict)
    event_probability_overrides: dict[str, float] = Field(default_factory=dict)
    starting_conditions: list[ConditionConfig] = Field(default_factory=list)
    event_flavor: dict[str, EventFlavor] | None = None
    narrative_style: str | None = None


def load_scenario(path: Path) -> ScenarioConfig:
    """Load and validate a scenario from a YAML file.

    Raises ValueError with descriptive messages on validation failures.
    """
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"Scenario file must be a YAML mapping, got {type(raw).__name__}")

    # Pydantic handles type validation and field constraints (ge/le)
    config = ScenarioConfig(**raw)

    # --- Custom validation beyond what Pydantic enforces ---

    # tech_era strings must be valid TechEra values
    valid_eras = {e.value for e in TechEra}
    for civ in config.civilizations:
        if civ.tech_era is not None and civ.tech_era not in valid_eras:
            raise ValueError(
                f"Invalid tech_era '{civ.tech_era}' for civ '{civ.name}'. "
                f"Valid values: {sorted(valid_eras)}"
            )

    # Relationship dispositions must be valid
    valid_disps = {d.value for d in Disposition}
    for civ_name, targets in config.relationships.items():
        for target_name, disp_str in targets.items():
            if disp_str not in valid_disps:
                raise ValueError(
                    f"Invalid disposition '{disp_str}' for {civ_name} -> {target_name}. "
                    f"Valid values: {sorted(valid_disps)}"
                )

    # Event probability override keys must be in DEFAULT_EVENT_PROBABILITIES
    for key, val in config.event_probability_overrides.items():
        if key not in VALID_EVENT_OVERRIDE_KEYS:
            raise ValueError(
                f"Invalid event type '{key}' in event_probability_overrides. "
                f"Valid types: {sorted(VALID_EVENT_OVERRIDE_KEYS)}. "
                f"Note: M7 cascade types (tech_advancement, coup, legacy, rival_fall) "
                f"are generated by simulation mechanics, not rolled for."
            )
        if not 0.0 <= val <= 1.0:
            raise ValueError(
                f"Event probability for '{key}' must be 0.0-1.0, got {val}"
            )

    # event_flavor keys must be valid event types
    if config.event_flavor:
        for key in config.event_flavor:
            if key not in VALID_EVENT_OVERRIDE_KEYS:
                raise ValueError(
                    f"Invalid event type '{key}' in event_flavor. "
                    f"Valid types: {sorted(VALID_EVENT_OVERRIDE_KEYS)}"
                )

    # leader_name_pool validation
    for civ in config.civilizations:
        if civ.leader_name_pool is not None:
            if len(civ.leader_name_pool) < 5:
                raise ValueError(
                    f"leader_name_pool for '{civ.name}' must have at least 5 names, "
                    f"got {len(civ.leader_name_pool)}"
                )

    # Cross-pool uniqueness
    all_pool_names: dict[str, str] = {}  # name -> civ that owns it
    for civ in config.civilizations:
        if civ.leader_name_pool:
            for name in civ.leader_name_pool:
                if name in all_pool_names:
                    raise ValueError(
                        f"Name '{name}' appears in leader_name_pool for both "
                        f"'{all_pool_names[name]}' and '{civ.name}'"
                    )
                all_pool_names[name] = civ.name

    # controller references must match defined civ names
    defined_civ_names = {c.name for c in config.civilizations}
    for region in config.regions:
        if region.controller is not None and region.controller != "none":
            if region.controller not in defined_civ_names:
                raise ValueError(
                    f"Region '{region.name}' controller '{region.controller}' "
                    f"not found in defined civilizations"
                )

    # num_civs >= len(civilizations)
    if config.num_civs is not None and config.num_civs < len(config.civilizations):
        raise ValueError(
            f"num_civs ({config.num_civs}) < number of defined civilizations "
            f"({len(config.civilizations)})"
        )

    # num_regions >= len(regions)
    if config.num_regions is not None and config.num_regions < len(config.regions):
        raise ValueError(
            f"num_regions ({config.num_regions}) < number of defined regions "
            f"({len(config.regions)})"
        )

    # num_regions >= num_civs (every civ needs at least one region)
    # Defaults duplicated here to avoid circular import with main.py
    _DEFAULT_NUM_CIVS = 4
    _DEFAULT_NUM_REGIONS = 8
    eff_civs = config.num_civs or max(len(config.civilizations), _DEFAULT_NUM_CIVS)
    eff_regions = config.num_regions or max(len(config.regions), _DEFAULT_NUM_REGIONS)
    if eff_regions < eff_civs:
        raise ValueError(
            f"num_regions ({eff_regions}) must be >= num_civs ({eff_civs}) — "
            f"every civilization needs at least one region"
        )

    return config


def apply_scenario(world: WorldState, config: ScenarioConfig) -> None:
    """Apply scenario overrides to a generated WorldState.

    Mutates world in-place. Call after generate_world() has produced the base state.
    """
    # --- Step 1: Region injection ---
    replaced_region_indices: set[int] = set()
    for reg_override in config.regions:
        target_idx = None
        for i, region in enumerate(world.regions):
            if i not in replaced_region_indices:
                target_idx = i
                break
        if target_idx is None:
            continue

        replaced_region_indices.add(target_idx)
        old_name = world.regions[target_idx].name
        new_name = reg_override.name

        # Apply overrides (non-None fields only)
        if reg_override.terrain is not None:
            world.regions[target_idx].terrain = reg_override.terrain
        if reg_override.carrying_capacity is not None:
            world.regions[target_idx].carrying_capacity = reg_override.carrying_capacity
        if reg_override.resources is not None:
            world.regions[target_idx].resources = reg_override.resources
        world.regions[target_idx].name = new_name

        # Update civ.regions list entries and region.controller
        if old_name != new_name:
            for civ in world.civilizations:
                civ.regions = [new_name if r == old_name else r for r in civ.regions]

    # --- Step 2: Civ injection ---
    replaced_civ_indices: set[int] = set()
    existing_civ_names = {c.name: i for i, c in enumerate(world.civilizations)}

    for civ_override in config.civilizations:
        # Name match: patch in-place
        if civ_override.name in existing_civ_names:
            target_idx = existing_civ_names[civ_override.name]
            replaced_civ_indices.add(target_idx)
            _apply_civ_override(world, target_idx, civ_override, rename=False)
            continue

        # No match: find next unreplaced slot
        target_idx = None
        for i in range(len(world.civilizations)):
            if i not in replaced_civ_indices:
                target_idx = i
                break
        if target_idx is None:
            continue

        replaced_civ_indices.add(target_idx)
        _apply_civ_override(world, target_idx, civ_override, rename=True)

    # --- Step 3: Relationship overrides ---
    explicit_pairs: set[tuple[str, str]] = set()
    for src, targets in config.relationships.items():
        for dst in targets:
            explicit_pairs.add((src, dst))

    for src, targets in config.relationships.items():
        for dst, disp_str in targets.items():
            disp = Disposition(disp_str)
            if src in world.relationships and dst in world.relationships[src]:
                world.relationships[src][dst].disposition = disp
            # Auto-symmetrize: fill reverse if not explicitly set
            if (dst, src) not in explicit_pairs:
                if dst in world.relationships and src in world.relationships[dst]:
                    world.relationships[dst][src].disposition = disp

    # --- Step 4: Event probability overrides ---
    world.event_probabilities.update(config.event_probability_overrides)

    # --- Step 5: Starting conditions ---
    for cond in config.starting_conditions:
        world.active_conditions.append(ActiveCondition(
            condition_type=cond.type,
            affected_civs=cond.affected,
            duration=cond.duration,
            severity=cond.severity,
        ))

    # --- Step 6: World name ---
    if config.world_name is not None:
        world.name = config.world_name

    # --- Post-apply validation ---
    civ_names = {c.name for c in world.civilizations}

    # (a) Every civ has at least one region
    for civ in world.civilizations:
        if not civ.regions:
            raise ValueError(
                f"Civ '{civ.name}' has no regions — "
                f"likely a controller name mismatch during injection"
            )

    # (b) All relationship references point to existing civ names
    for src in world.relationships:
        if src not in civ_names:
            raise ValueError(f"Relationship source '{src}' not found in civilizations")
        for dst in world.relationships[src]:
            if dst not in civ_names:
                raise ValueError(f"Relationship target '{dst}' not found in civilizations")

    # (c) Starting condition affected civs all exist
    for cond in world.active_conditions:
        for affected in cond.affected_civs:
            if affected not in civ_names:
                raise ValueError(
                    f"Starting condition '{cond.condition_type}' references "
                    f"unknown civ '{affected}'"
                )


def _apply_civ_override(
    world: WorldState, idx: int, override: CivOverride, rename: bool,
) -> None:
    """Apply a CivOverride to the civilization at the given index."""
    civ = world.civilizations[idx]
    old_name = civ.name

    # Apply stat overrides (non-None only)
    if override.population is not None:
        civ.population = override.population
    if override.military is not None:
        civ.military = override.military
    if override.economy is not None:
        civ.economy = override.economy
    if override.culture is not None:
        civ.culture = override.culture
    if override.stability is not None:
        civ.stability = override.stability
    if override.treasury is not None:
        civ.treasury = override.treasury
    if override.asabiya is not None:
        civ.asabiya = override.asabiya
    if override.tech_era is not None:
        civ.tech_era = TechEra(override.tech_era)
    if override.domains is not None:
        civ.domains = override.domains
    if override.values is not None:
        civ.values = override.values
    if override.goal is not None:
        civ.goal = override.goal

    # Leader override
    # NOTE: generate_world now seeds used_leader_names with initial leader
    # names, so the old_leader_name lookup below will always find a match
    # for freshly-generated worlds. The else branch remains as a safety net
    # for manually constructed WorldState objects in tests.
    if override.leader is not None:
        if override.leader.name is not None:
            old_leader_name = civ.leader.name
            civ.leader.name = override.leader.name
            # Update used_leader_names to prevent succession duplicates
            if old_leader_name in world.used_leader_names:
                leader_idx = world.used_leader_names.index(old_leader_name)
                world.used_leader_names[leader_idx] = override.leader.name
            else:
                world.used_leader_names.append(override.leader.name)
        if override.leader.trait is not None:
            civ.leader.trait = override.leader.trait

    # Rename civ if needed
    if rename:
        new_name = override.name
        civ.name = new_name

        # Update region controllers
        for region in world.regions:
            if region.controller == old_name:
                region.controller = new_name

        # Update relationship keys
        if old_name in world.relationships:
            world.relationships[new_name] = world.relationships.pop(old_name)
        for other_name in list(world.relationships.keys()):
            if old_name in world.relationships[other_name]:
                world.relationships[other_name][new_name] = world.relationships[other_name].pop(old_name)

        # Update action_history keys
        if old_name in world.action_history:
            world.action_history[new_name] = world.action_history.pop(old_name)


def _resolve(cli_val, scenario_val, default):
    """CLI wins if explicitly set (not None), else scenario, else hardcoded default."""
    if cli_val is not None:
        return cli_val
    if scenario_val is not None:
        return scenario_val
    return default


def resolve_scenario_params(config: ScenarioConfig, cli_args) -> dict:
    """Merge scenario config with CLI args.

    CLI args use None as sentinel default (argparse default=None).
    Precedence: explicit CLI > scenario YAML > hardcoded default.

    Returns dict with keys: seed, num_turns, num_civs, num_regions,
    reflection_interval, scenario_config.
    """
    if getattr(cli_args, "resume", None):
        raise ValueError("--scenario and --resume are mutually exclusive")

    seed = _resolve(cli_args.seed, config.seed, 42)
    num_turns = _resolve(cli_args.turns, config.num_turns, 50)
    reflection_interval = _resolve(cli_args.reflection_interval, config.reflection_interval, 10)

    # For num_civs/num_regions: take max of resolved value and defined entity count
    # NOTE: generate_regions now raises ValueError if count > 12 (template pool
    # size), so we validate here to give a friendlier error message early.
    # Hardcoded defaults only apply when no defined entities exist
    civ_default = len(config.civilizations) if config.civilizations else 4
    region_default = len(config.regions) if config.regions else 8
    base_civs = _resolve(cli_args.civs, config.num_civs, civ_default)
    base_regions = _resolve(cli_args.regions, config.num_regions, region_default)
    num_civs = max(base_civs, len(config.civilizations))
    num_regions = max(base_regions, len(config.regions))
    if num_regions > len(REGION_TEMPLATES):
        raise ValueError(
            f"Scenario requires {num_regions} regions but only "
            f"{len(REGION_TEMPLATES)} region templates exist"
        )

    return {
        "seed": seed,
        "num_turns": num_turns,
        "num_civs": num_civs,
        "num_regions": num_regions,
        "reflection_interval": reflection_interval,
        "scenario_config": config,
    }
