"""Scenario loading — YAML-based scenario configs that override generate_world output."""
from __future__ import annotations

from pathlib import Path
from typing import Optional

import yaml
from pydantic import BaseModel, Field

from chronicler.models import (
    ActiveCondition, Civilization, ClimateConfig, Disposition, Region, Relationship,
    River, TechEra, TerrainTransitionRule, WorldState,
    ResourceType, EMPTY_SLOT,
)
from chronicler.utils import sync_civ_population
from chronicler.world_gen import DEFAULT_EVENT_PROBABILITIES, REGION_TEMPLATES
from chronicler.leaders import strip_title


# Valid event types for probability overrides (M7 cascade types are NOT valid targets —
# tech_advancement, coup, legacy, rival_fall are generated by simulation mechanics, not rolled for)
VALID_EVENT_OVERRIDE_KEYS = set(DEFAULT_EVENT_PROBABILITIES.keys())

VALID_INTERESTINGNESS_KEYS = {
    "war_count", "collapse_count", "named_event_count",
    "distinct_action_count", "reflection_count",
    "tech_advancement_count", "max_stat_swing",
}


class EventFlavor(BaseModel):
    name: str
    description: str


class LeaderOverride(BaseModel):
    name: str | None = None
    trait: str | None = None


class RegionOverride(BaseModel):
    name: str
    terrain: str | None = None
    carrying_capacity: int | None = Field(default=None, ge=1, le=100)
    resources: str | None = None
    controller: str | None = None
    x: float | None = None
    y: float | None = None
    adjacencies: list[str] | None = None
    specialized_resources: list[str] | None = None
    ecology: dict[str, float] | None = None


class CivOverride(BaseModel):
    name: str
    population: int | None = Field(default=None, ge=1, le=1000)
    military: int | None = Field(default=None, ge=0, le=100)
    economy: int | None = Field(default=None, ge=0, le=100)
    culture: int | None = Field(default=None, ge=0, le=100)
    stability: int | None = Field(default=None, ge=0, le=100)
    treasury: int | None = Field(default=None, ge=0)
    asabiya: float | None = Field(default=None, ge=0.0, le=1.0)
    tech_era: str | None = None
    domains: list[str] | None = None
    values: list[str] | None = None
    goal: str | None = None
    leader: LeaderOverride | None = None
    leader_name_pool: list[str] | None = None
    capital: str | None = None


class ConditionConfig(BaseModel):
    type: str
    affected: list[str]
    duration: int = Field(ge=1)
    severity: int = Field(ge=1, le=100)


class ScenarioConfig(BaseModel):
    name: str
    description: str = ""
    world_name: str | None = None
    seed: int | None = None
    num_civs: int | None = None
    num_regions: int | None = None
    num_turns: int | None = None
    reflection_interval: int | None = None
    regions: list[RegionOverride] = Field(default_factory=list)
    civilizations: list[CivOverride] = Field(default_factory=list)
    relationships: dict[str, dict[str, str]] = Field(default_factory=dict)
    event_probability_overrides: dict[str, float] = Field(default_factory=dict)
    starting_conditions: list[ConditionConfig] = Field(default_factory=list)
    event_flavor: dict[str, EventFlavor] | None = None
    narrative_style: str | None = None
    interestingness_weights: dict[str, float] | None = None
    secession_pool: list[CivOverride] = Field(default_factory=list)
    climate: "ClimateConfig | None" = None
    fog_of_war: bool | None = None
    chaos_multiplier: float = Field(default=1.0, ge=0.0)
    black_swan_cooldown_turns: int = Field(default=30, ge=0)
    terrain_transition_rules: list[TerrainTransitionRule] | None = None  # None = use WorldState defaults
    rivers: list[River] = Field(default_factory=list)


def load_scenario(path: Path) -> ScenarioConfig:
    """Load and validate a scenario from a YAML file.

    Raises ValueError with descriptive messages on validation failures.
    """
    raw = yaml.safe_load(path.read_text())
    if not isinstance(raw, dict):
        raise ValueError(f"Scenario file must be a YAML mapping, got {type(raw).__name__}")

    # Pydantic handles type validation and field constraints (ge/le)
    config = ScenarioConfig(**raw)

    # --- Custom validation beyond what Pydantic enforces ---

    # tech_era strings must be valid TechEra values
    valid_eras = {e.value for e in TechEra}
    for civ in config.civilizations:
        if civ.tech_era is not None and civ.tech_era not in valid_eras:
            raise ValueError(
                f"Invalid tech_era '{civ.tech_era}' for civ '{civ.name}'. "
                f"Valid values: {sorted(valid_eras)}"
            )

    # Relationship dispositions must be valid
    valid_disps = {d.value for d in Disposition}
    for civ_name, targets in config.relationships.items():
        for target_name, disp_str in targets.items():
            if disp_str not in valid_disps:
                raise ValueError(
                    f"Invalid disposition '{disp_str}' for {civ_name} -> {target_name}. "
                    f"Valid values: {sorted(valid_disps)}"
                )

    # Event probability override keys must be in DEFAULT_EVENT_PROBABILITIES
    for key, val in config.event_probability_overrides.items():
        if key not in VALID_EVENT_OVERRIDE_KEYS:
            raise ValueError(
                f"Invalid event type '{key}' in event_probability_overrides. "
                f"Valid types: {sorted(VALID_EVENT_OVERRIDE_KEYS)}. "
                f"Note: M7 cascade types (tech_advancement, coup, legacy, rival_fall) "
                f"are generated by simulation mechanics, not rolled for."
            )
        if not 0.0 <= val <= 1.0:
            raise ValueError(
                f"Event probability for '{key}' must be 0.0-1.0, got {val}"
            )

    # event_flavor keys must be valid event types
    if config.event_flavor:
        for key in config.event_flavor:
            if key not in VALID_EVENT_OVERRIDE_KEYS:
                raise ValueError(
                    f"Invalid event type '{key}' in event_flavor. "
                    f"Valid types: {sorted(VALID_EVENT_OVERRIDE_KEYS)}"
                )

    # leader_name_pool validation
    for civ in config.civilizations:
        if civ.leader_name_pool is not None:
            if len(civ.leader_name_pool) < 5:
                raise ValueError(
                    f"leader_name_pool for '{civ.name}' must have at least 5 names, "
                    f"got {len(civ.leader_name_pool)}"
                )

    # Cross-pool uniqueness
    all_pool_names: dict[str, str] = {}  # name -> civ that owns it
    for civ in config.civilizations:
        if civ.leader_name_pool:
            for name in civ.leader_name_pool:
                if name in all_pool_names:
                    raise ValueError(
                        f"Name '{name}' appears in leader_name_pool for both "
                        f"'{all_pool_names[name]}' and '{civ.name}'"
                    )
                all_pool_names[name] = civ.name

    # controller references must match defined civ names
    defined_civ_names = {c.name for c in config.civilizations}
    for region in config.regions:
        if region.controller is not None and region.controller != "none":
            if region.controller not in defined_civ_names:
                raise ValueError(
                    f"Region '{region.name}' controller '{region.controller}' "
                    f"not found in defined civilizations"
                )

    # num_civs >= len(civilizations)
    if config.num_civs is not None and config.num_civs < len(config.civilizations):
        raise ValueError(
            f"num_civs ({config.num_civs}) < number of defined civilizations "
            f"({len(config.civilizations)})"
        )

    # num_regions >= len(regions)
    if config.num_regions is not None and config.num_regions < len(config.regions):
        raise ValueError(
            f"num_regions ({config.num_regions}) < number of defined regions "
            f"({len(config.regions)})"
        )

    # num_regions >= num_civs (every civ needs at least one region)
    # Defaults duplicated here to avoid circular import with main.py
    _DEFAULT_NUM_CIVS = 4
    _DEFAULT_NUM_REGIONS = 8
    eff_civs = config.num_civs or max(len(config.civilizations), _DEFAULT_NUM_CIVS)
    eff_regions = config.num_regions or max(len(config.regions), _DEFAULT_NUM_REGIONS)
    if eff_regions < eff_civs:
        raise ValueError(
            f"num_regions ({eff_regions}) must be >= num_civs ({eff_civs}) — "
            f"every civilization needs at least one region"
        )

    # Interestingness weight keys must be valid metric names
    if config.interestingness_weights:
        for key in config.interestingness_weights:
            if key not in VALID_INTERESTINGNESS_KEYS:
                raise ValueError(
                    f"Invalid interestingness weight key '{key}'. "
                    f"Valid keys: {sorted(VALID_INTERESTINGNESS_KEYS)}"
                )

    return config


def apply_scenario(world: WorldState, config: ScenarioConfig) -> None:
    """Apply scenario overrides to a generated WorldState.

    Mutates world in-place. Call after generate_world() has produced the base state.
    """
    # --- Step 1: Region injection ---
    replaced_region_indices: set[int] = set()
    region_override_map: list[tuple[int, RegionOverride]] = []
    for reg_override in config.regions:
        target_idx = None
        for i, region in enumerate(world.regions):
            if i not in replaced_region_indices:
                target_idx = i
                break
        if target_idx is None:
            continue

        replaced_region_indices.add(target_idx)
        region_override_map.append((target_idx, reg_override))
        old_name = world.regions[target_idx].name
        new_name = reg_override.name

        # Apply overrides (non-None fields only)
        if reg_override.terrain is not None:
            world.regions[target_idx].terrain = reg_override.terrain
        if reg_override.carrying_capacity is not None:
            world.regions[target_idx].carrying_capacity = reg_override.carrying_capacity
        if reg_override.resources is not None:
            world.regions[target_idx].resources = reg_override.resources
        world.regions[target_idx].name = new_name
        if reg_override.x is not None:
            world.regions[target_idx].x = reg_override.x
        if reg_override.y is not None:
            world.regions[target_idx].y = reg_override.y
        if reg_override.adjacencies is not None:
            world.regions[target_idx].adjacencies = reg_override.adjacencies
        if reg_override.specialized_resources is not None:
            from chronicler.models import Resource
            from chronicler.resources import populate_legacy_resources, RESOURCE_BASE
            try:
                types = [int(r) for r in reg_override.specialized_resources]
                for i, rtype in enumerate(types[:3]):
                    world.regions[target_idx].resource_types[i] = rtype
                    world.regions[target_idx].resource_base_yields[i] = RESOURCE_BASE.get(rtype, 1.0)
                populate_legacy_resources([world.regions[target_idx]])
            except (ValueError, TypeError):
                world.regions[target_idx].specialized_resources = [Resource(r) for r in reg_override.specialized_resources]
        if reg_override.ecology is not None:
            for key, value in reg_override.ecology.items():
                setattr(world.regions[target_idx].ecology, key, value)

        # Update civ.regions list entries and region.controller
        if old_name != new_name:
            for civ in world.civilizations:
                civ.regions = [new_name if r == old_name else r for r in civ.regions]

    # --- Step 2: Civ injection ---
    replaced_civ_indices: set[int] = set()
    existing_civ_names = {c.name: i for i, c in enumerate(world.civilizations)}

    for civ_override in config.civilizations:
        # Name match: patch in-place
        if civ_override.name in existing_civ_names:
            target_idx = existing_civ_names[civ_override.name]
            replaced_civ_indices.add(target_idx)
            _apply_civ_override(world, target_idx, civ_override, rename=False)
            continue

        # No match: find next unreplaced slot
        target_idx = None
        for i in range(len(world.civilizations)):
            if i not in replaced_civ_indices:
                target_idx = i
                break
        if target_idx is None:
            continue

        replaced_civ_indices.add(target_idx)
        _apply_civ_override(world, target_idx, civ_override, rename=True)

    # --- Step 2b: Region controller overrides ---
    # Build a set of all region names currently in region_override_map (being reassigned)
    reassigned_region_names = {world.regions[i].name for i, _ in region_override_map}
    for target_idx, reg_override in region_override_map:
        if reg_override.controller is None:
            continue
        region = world.regions[target_idx]
        old_controller = region.controller

        # Remove region from old controller's region list
        if old_controller:
            for civ in world.civilizations:
                if civ.name == old_controller:
                    civ.regions = [r for r in civ.regions if r != region.name]
                    # If old controller now has no regions, give it a fallback uncontrolled region
                    if not civ.regions:
                        for fallback in world.regions:
                            if fallback.controller is None and fallback.name not in reassigned_region_names:
                                fallback.controller = civ.name
                                civ.regions.append(fallback.name)
                                break

        if reg_override.controller == "none":
            region.controller = None
        else:
            region.controller = reg_override.controller
            for civ in world.civilizations:
                if civ.name == reg_override.controller and region.name not in civ.regions:
                    civ.regions.append(region.name)

    # --- Step 3: Relationship overrides ---
    explicit_pairs: set[tuple[str, str]] = set()
    for src, targets in config.relationships.items():
        for dst in targets:
            explicit_pairs.add((src, dst))

    for src, targets in config.relationships.items():
        for dst, disp_str in targets.items():
            disp = Disposition(disp_str)
            if src in world.relationships and dst in world.relationships[src]:
                world.relationships[src][dst].disposition = disp
            # Auto-symmetrize: fill reverse if not explicitly set
            if (dst, src) not in explicit_pairs:
                if dst in world.relationships and src in world.relationships[dst]:
                    world.relationships[dst][src].disposition = disp

    # --- Step 4: Event probability overrides ---
    world.event_probabilities.update(config.event_probability_overrides)

    # --- Step 5: Starting conditions ---
    for cond in config.starting_conditions:
        world.active_conditions.append(ActiveCondition(
            condition_type=cond.type,
            affected_civs=cond.affected,
            duration=cond.duration,
            severity=cond.severity,
        ))

    # --- Step 6: World name ---
    if config.world_name is not None:
        world.name = config.world_name

    # --- Step 7: Record scenario name ---
    world.scenario_name = config.name

    # --- Step 7b: Climate and fog of war ---
    if config.climate is not None:
        world.climate_config = config.climate
    if config.fog_of_war is not None:
        world.fog_of_war = config.fog_of_war

    # --- Step 7c: M18 emergence config ---
    world.chaos_multiplier = config.chaos_multiplier
    world.black_swan_cooldown_turns = config.black_swan_cooldown_turns
    if config.terrain_transition_rules is not None:
        world.terrain_transition_rules = list(config.terrain_transition_rules)

    # --- Step 8: Recompute adjacencies (fills gaps for regions without explicit adjacencies) ---
    # Clear stale adjacencies from generate_world (region names may have changed)
    from chronicler.adjacency import compute_adjacencies
    for region in world.regions:
        if not any(ro.name == region.name and ro.adjacencies is not None for ro in config.regions):
            region.adjacencies = []
    compute_adjacencies(world.regions)
    from chronicler.resources import assign_resources
    assign_resources(world.regions, seed=world.seed)
    from chronicler.resources import assign_resource_types, populate_legacy_resources
    assign_resource_types(world.regions, seed=world.seed)
    populate_legacy_resources(world.regions)

    # --- Step 9: River assignment (M35a) ---
    if len(config.rivers) > 32:
        raise ValueError(f"Maximum 32 rivers supported (got {len(config.rivers)})")
    region_map = {r.name: r for r in world.regions}
    world.rivers = []
    for river_idx, river in enumerate(config.rivers):
        for rname in river.path:
            if rname not in region_map:
                raise ValueError(f"River '{river.name}': region '{rname}' not found in scenario")
        for i in range(len(river.path) - 1):
            r_curr = region_map[river.path[i]]
            r_next_name = river.path[i + 1]
            if r_next_name not in r_curr.adjacencies:
                raise ValueError(
                    f"River '{river.name}': '{river.path[i]}' and '{r_next_name}' are not adjacent"
                )
        world.rivers.append(river)
    # Assign river_mask bits
    for river_idx, river in enumerate(world.rivers):
        bit = 1 << river_idx
        for rname in river.path:
            region_map[rname].river_mask |= bit

    # Apply river bonuses (once per region, not per river)
    from chronicler.tuning import get_override, K_RIVER_WATER_BONUS, K_RIVER_CAPACITY_MULTIPLIER
    from chronicler.ecology import _clamp_ecology
    from chronicler.resources import RESOURCE_BASE
    import random as _rng_mod
    water_bonus = get_override(world, K_RIVER_WATER_BONUS, 0.15)
    cap_mult = get_override(world, K_RIVER_CAPACITY_MULTIPLIER, 1.2)
    for region in world.regions:
        if region.river_mask == 0:
            continue
        # Water baseline
        region.ecology.water += water_bonus
        _clamp_ecology(region)
        # Carrying capacity
        region.carrying_capacity = int(region.carrying_capacity * cap_mult)
        # Fish resource (Phoebe N-2: must also set base_yield)
        if ResourceType.FISH not in region.resource_types:
            for slot in range(3):
                if region.resource_types[slot] == EMPTY_SLOT:
                    region.resource_types[slot] = ResourceType.FISH
                    rng = _rng_mod.Random(world.seed + hash(region.name) + 0xF15F)
                    variance = rng.uniform(-0.2, 0.2)
                    region.resource_base_yields[slot] = RESOURCE_BASE[ResourceType.FISH] * (1.0 + variance)
                    break

    # --- Post-apply validation ---
    civ_names = {c.name for c in world.civilizations}

    # (a) Every civ has at least one region
    for civ in world.civilizations:
        if not civ.regions:
            raise ValueError(
                f"Civ '{civ.name}' has no regions — "
                f"likely a controller name mismatch during injection"
            )

    # (b) All relationship references point to existing civ names
    for src in world.relationships:
        if src not in civ_names:
            raise ValueError(f"Relationship source '{src}' not found in civilizations")
        for dst in world.relationships[src]:
            if dst not in civ_names:
                raise ValueError(f"Relationship target '{dst}' not found in civilizations")

    # (c) Starting condition affected civs all exist
    for cond in world.active_conditions:
        for affected in cond.affected_civs:
            if affected not in civ_names:
                raise ValueError(
                    f"Starting condition '{cond.condition_type}' references "
                    f"unknown civ '{affected}'"
                )


def _apply_civ_override(
    world: WorldState, idx: int, override: CivOverride, rename: bool,
) -> None:
    """Apply a CivOverride to the civilization at the given index."""
    civ = world.civilizations[idx]
    old_name = civ.name

    # Apply stat overrides (non-None only)
    if override.population is not None:
        civ.population = override.population
        # Distribute override population across civ's regions
        from chronicler.ecology import effective_capacity
        civ_regions = [r for r in world.regions if r.controller == civ.name]
        if civ_regions:
            total_cap = sum(effective_capacity(r) for r in civ_regions)
            remainder = override.population
            for j, cr in enumerate(civ_regions):
                if j == len(civ_regions) - 1:
                    cr.population = remainder
                else:
                    share = (
                        round(override.population * effective_capacity(cr) / total_cap)
                        if total_cap > 0
                        else override.population // len(civ_regions)
                    )
                    cr.population = share
                    remainder -= share
        sync_civ_population(civ, world)
    if override.military is not None:
        civ.military = override.military
    if override.economy is not None:
        civ.economy = override.economy
    if override.culture is not None:
        civ.culture = override.culture
    if override.stability is not None:
        civ.stability = override.stability
    if override.treasury is not None:
        civ.treasury = override.treasury
    if override.asabiya is not None:
        civ.asabiya = override.asabiya
    if override.tech_era is not None:
        civ.tech_era = TechEra(override.tech_era)
    if override.domains is not None:
        civ.domains = override.domains
    if override.values is not None:
        civ.values = override.values
    if override.goal is not None:
        civ.goal = override.goal

    # Leader override
    # NOTE: generate_world now seeds used_leader_names with initial leader
    # names, so the old_leader_name lookup below will always find a match
    # for freshly-generated worlds. The else branch remains as a safety net
    # for manually constructed WorldState objects in tests.
    if override.leader is not None:
        if override.leader.name is not None:
            old_leader_name = civ.leader.name
            civ.leader.name = override.leader.name
            # Update used_leader_names to prevent succession duplicates
            if old_leader_name in world.used_leader_names:
                leader_idx = world.used_leader_names.index(old_leader_name)
                world.used_leader_names[leader_idx] = override.leader.name
            else:
                world.used_leader_names.append(override.leader.name)
            # M51: Seed regnal_name_counts for the overridden leader's throne_name
            throne_name = strip_title(override.leader.name)
            civ.leader.throne_name = throne_name
            # Remove old leader's throne_name from counts if it was tracked
            old_throne = strip_title(old_leader_name)
            if old_throne in civ.regnal_name_counts:
                civ.regnal_name_counts[old_throne] = max(0, civ.regnal_name_counts[old_throne] - 1)
                if civ.regnal_name_counts[old_throne] == 0:
                    del civ.regnal_name_counts[old_throne]
            # Seed the new throne_name count
            civ.regnal_name_counts[throne_name] = civ.regnal_name_counts.get(throne_name, 0) + 1
        if override.leader.trait is not None:
            civ.leader.trait = override.leader.trait

    # Leader name pool
    if override.leader_name_pool is not None:
        civ.leader_name_pool = override.leader_name_pool

    # Capital override
    if override.capital is not None:
        civ.capital_region = override.capital

    # Rename civ if needed
    if rename:
        new_name = override.name
        civ.name = new_name

        # Update region controllers
        for region in world.regions:
            if region.controller == old_name:
                region.controller = new_name

        # Update relationship keys
        if old_name in world.relationships:
            world.relationships[new_name] = world.relationships.pop(old_name)
        for other_name in list(world.relationships.keys()):
            if old_name in world.relationships[other_name]:
                world.relationships[other_name][new_name] = world.relationships[other_name].pop(old_name)

        # Update action_history keys
        if old_name in world.action_history:
            world.action_history[new_name] = world.action_history.pop(old_name)


def _resolve(cli_val, scenario_val, default):
    """CLI wins if explicitly set (not None), else scenario, else hardcoded default."""
    if cli_val is not None:
        return cli_val
    if scenario_val is not None:
        return scenario_val
    return default


def resolve_scenario_params(config: ScenarioConfig, cli_args) -> dict:
    """Merge scenario config with CLI args.

    CLI args use None as sentinel default (argparse default=None).
    Precedence: explicit CLI > scenario YAML > hardcoded default.

    Returns dict with keys: seed, num_turns, num_civs, num_regions,
    reflection_interval, scenario_config.
    """
    if getattr(cli_args, "resume", None):
        raise ValueError("--scenario and --resume are mutually exclusive")

    seed = _resolve(cli_args.seed, config.seed, 42)
    num_turns = _resolve(cli_args.turns, config.num_turns, 50)
    reflection_interval = _resolve(cli_args.reflection_interval, config.reflection_interval, 10)

    # For num_civs/num_regions: take max of resolved value and defined entity count
    # NOTE: generate_regions now raises ValueError if count > 12 (template pool
    # size), so we validate here to give a friendlier error message early.
    # Hardcoded defaults only apply when no defined entities exist
    civ_default = len(config.civilizations) if config.civilizations else 4
    region_default = len(config.regions) if config.regions else 8
    base_civs = _resolve(cli_args.civs, config.num_civs, civ_default)
    base_regions = _resolve(cli_args.regions, config.num_regions, region_default)
    num_civs = max(base_civs, len(config.civilizations))
    num_regions = max(base_regions, len(config.regions))
    if num_regions > len(REGION_TEMPLATES):
        raise ValueError(
            f"Scenario requires {num_regions} regions but only "
            f"{len(REGION_TEMPLATES)} region templates exist"
        )

    return {
        "seed": seed,
        "num_turns": num_turns,
        "num_civs": num_civs,
        "num_regions": num_regions,
        "reflection_interval": reflection_interval,
        "scenario_config": config,
    }
